### ISSUE TITLE
Trained checkpoint?

### ISSUE THREAD

**Issue by yangkevin2** [takase/control-length#2]
Hi, 

Thanks for the great repo. I'm wondering if you can provide a checkpoint file for text summarization that has been trained on gigaword according to your settings? I'm trying to train according to the provided settings for train.py, and at this rate on 4 GPUs it will take me 2 weeks. (I had to set limits on max-tokens and max-sentences, because otherwise I get memory problems and the job hangs.)

**Comment by takase** [comment]
I uploaded pre-trained LRPE + PE model in English dataset.
Please get from here: https://drive.google.com/file/d/15Sy8rv6Snw6Nso7T5MxYHSAZDdieXpE7/view?usp=sharing

**Comment by yangkevin2** [comment]
Thanks!
