### ISSUE TITLE
gigawod dataset

### ISSUE THREAD

**Issue by YoonaX** [takase/control-length#3]
hi，could you put a download link to the annotated Gigaword dataset？Thanks~

**Comment by takase** [comment]
I'm sorry I can't distribute the original annotated English Gigaword due to the [license of LDC](https://catalog.ldc.upenn.edu/LDC2012T21).

However, pre-processed dataset can be obtained from [here](https://github.com/harvardnlp/sent-summary).

**Comment by YoonaX** [comment]
OK~Thanks~

**Comment by YoonaX** [comment]
OK~ Thanks~
