### ISSUE TITLE
Use of `padding_idx` in SinusoidalPositionalEmbedding

### ISSUE THREAD

**Issue by mandalbiswadip** [takase/control-length#7]
I was trying to use the code for my project and I couldn't figure out why the weights are going to zero at positional_idx [here](https://github.com/takase/control-length/blob/c9eb632e112f07a156a5892065969cda788253a0/encdec/fairseq/modules/sinusoidal_positional_embedding.py#L67):
I am refering this part of the code.
```
if padding_idx is not None:
            if length is None:
                emb[padding_idx, :] = 0
            else:
                emb[:, padding_idx, :] = 0
```

I understand that the `padding_idx` can be used to get the masks where the position embedding should go to zero and I believe the `utils.make_positions` function does exactly that. However, I couldn't figure out the above piece of code.

**Comment by takase** [comment]
This part inserts 0 instead of sinusoidal position embeddings into the positions of padding_idx.
utils.make_positions makes positions, that is not the sinusoidal position embedding.
The original fairseq also adopts such codes.
